spring.application.name=Emsystem

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/user_data
spring.datasource.username=root
spring.datasource.password=Sai@86886
spring.main.allow-bean-definition-overriding=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.employeemanagement=DEBUG
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=Oo+QtKjuisiIKvdnGj65JiGupJPWLpK/5zm944rHGrs=
jwt.refreshExpirationMs=86400000
jwt.expirationMs=3600000

